require:
  - rubocop-rspec

AllCops:
  Exclude:
    - "public/*"
  Include:
    - "Gemfile.*"

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

# When testing instantiation, it's perfectly valid to stub any instance
RSpec/AnyInstance:
  Enabled: false

Style/Documentation:
  Exclude:
    - "spec/**/*"
    - "Rakefile"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "Rakefile"

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/LineLength:
  Max: 80

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Style/FormatStringToken:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Enabled: false

inherit_from: .rubocop_todo.yml
