sudo: false
language: ruby
cache: bundler
jobs:
  include:
    - name: "specs"
      script:
        - "bundle exec rails spec"
    - name: "style"
      script:
        - "bundle exec rubocop -v"
        - "bundle exec rubocop"
